<?php
// Ensure the Database connection class is available
// Assuming this model file is one level down from the config file
require_once __DIR__ . '/../config/Database.php';

class User {
    private $conn;
    private $users_table = "users";
    private $admins_table = "admins";

    /**
     * Constructor - initialize database connection
     */
    public function __construct() {
        $database = new Database();
        $this->conn = $database->connect();
    }

    /**
     * Finds a passenger user by email address.
     * Used for passenger login.
     *
     * @param string $email
     * @return array|false The user record or false if not found.
     */
    public function findUserByEmail($email) {
        // SQL query to select all columns for a user based on email
        $query = "SELECT user_id, email, password_hash, first_name, last_name, phone_number
                  FROM " . $this->users_table . "
                  WHERE email = :email
                  LIMIT 0,1";

        // Prepare statement
        $stmt = $this->conn->prepare($query);

        // Sanitize email input (remove potential HTML or PHP tags)
        $email = htmlspecialchars(strip_tags($email));

        // Bind email value
        $stmt->bindParam(":email", $email);

        // Execute query
        $stmt->execute();

        // Fetch the result
        $row = $stmt->fetch(PDO::FETCH_ASSOC);

        // Return the row if found, otherwise false
        return $row;
    }

    /**
     * Finds an admin user by email address.
     * Used for admin login.
     *
     * @param string $email
     * @return array|false The admin record or false if not found.
     */
    public function findAdminByEmail($email) {
        // SQL query to select all columns for an admin based on email
        $query = "SELECT admin_id, email, password_hash, full_name, role
                  FROM " . $this->admins_table . "
                  WHERE email = :email
                  LIMIT 0,1";

        // Prepare statement
        $stmt = $this->conn->prepare($query);

        // Sanitize email input
        $email = htmlspecialchars(strip_tags($email));

        // Bind email value
        $stmt->bindParam(":email", $email);

        // Execute query
        $stmt->execute();

        // Fetch the result
        $row = $stmt->fetch(PDO::FETCH_ASSOC);

        // Return the row if found, otherwise false
        return $row;
    }

    /**
     * Creates a new user (passenger) record in the database.
     *
     * @param array $data Contains first_name, last_name, email, phone_number, and password_hash
     * @return bool True on successful insertion, false otherwise.
     */
    public function registerUser($data) {
        // Simple check to prevent duplicate email registration
        if ($this->findUserByEmail($data['email'])) {
            return false; // Email already registered
        }

        // SQL query to insert a new user
        $query = "INSERT INTO " . $this->users_table . " 
                  (first_name, last_name, email, phone_number, password_hash)
                  VALUES (:first_name, :last_name, :email, :phone_number, :password_hash)";

        // Prepare statement
        $stmt = $this->conn->prepare($query);

        // Sanitize and bind parameters
        $stmt->bindParam(":first_name", htmlspecialchars(strip_tags($data['first_name'])));
        $stmt->bindParam(":last_name", htmlspecialchars(strip_tags($data['last_name'])));
        $stmt->bindParam(":email", htmlspecialchars(strip_tags($data['email'])));
        $stmt->bindParam(":phone_number", htmlspecialchars(strip_tags($data['phone_number'])));
        $stmt->bindParam(":password_hash", $data['password_hash']); // Hash is already generated by controller

        // Execute query
        if ($stmt->execute()) {
            return true;
        }

        // Return false on execution failure
        return false;
    }
}
?>