<?php
// models/User.php

// Ensure the Database connection class is available
require_once __DIR__ . '/../config/Database.php'; // Corrected path to config/Database.php

class User {
    private $conn;
    private $users_table = "users";
    private $admins_table = "admins";

    /**
     * Constructor - initialize database connection
     */
    public function __construct() {
        $database = new Database();
        // Assuming your Database class has a 'connect' method that returns a PDO object
        $this->conn = $database->connect(); 
    }

    /**
     * Finds a passenger user by email address.
     * Note: Uses 'password_hash' column for stored password
     */
    public function findUserByEmail($email) {
        $query = "SELECT user_id, email, password_hash, first_name, last_name, phone_number
                     FROM " . $this->users_table . "
                     WHERE email = :email
                     LIMIT 0,1";

        $stmt = $this->conn->prepare($query);
        $email = htmlspecialchars(strip_tags($email));
        $stmt->bindParam(":email", $email);
        $stmt->execute();
        
        // Fetch the result
        return $stmt->fetch(PDO::FETCH_ASSOC);
    }

    /**
     * Creates a new user (passenger) record in the database.
     *
     * @param array $data Contains first_name, last_name, email, phone_number, and password_hash
     * @return bool True on successful insertion, false otherwise.
     */
    public function registerUser($data) { // <-- CORRECT METHOD NAME!
        
        // SQL query to insert a new user
        $query = "INSERT INTO " . $this->users_table . " 
                     (first_name, last_name, email, phone_number, password_hash)
                     VALUES (:first_name, :last_name, :email, :phone_number, :password_hash)";

        // Prepare statement
        $stmt = $this->conn->prepare($query);

        // Sanitize and bind parameters
        $firstName = htmlspecialchars(strip_tags($data['first_name']));
        $lastName = htmlspecialchars(strip_tags($data['last_name']));
        $email = htmlspecialchars(strip_tags($data['email']));
        $phoneNumber = htmlspecialchars(strip_tags($data['phone_number']));

        $stmt->bindParam(":first_name", $firstName);
        $stmt->bindParam(":last_name", $lastName);
        $stmt->bindParam(":email", $email);
        $stmt->bindParam(":phone_number", $phoneNumber);
        $stmt->bindParam(":password_hash", $data['password_hash']); // Hash is already generated by controller

        // Execute query
        return $stmt->execute();
    }
    
    // NOTE: findAdminByEmail remains here but is typically unused by the AuthController.
    // It's usually moved to an Admin model or left here if User handles both.
    public function findAdminByEmail($email) {
        // ... (your existing admin query logic)
        $query = "SELECT admin_id, email, password_hash, full_name, role
                      FROM " . $this->admins_table . "
                      WHERE email = :email
                      LIMIT 0,1";
        // Prepare, sanitize, bind, and execute...
        $stmt = $this->conn->prepare($query);
        $email = htmlspecialchars(strip_tags($email));
        $stmt->bindParam(":email", $email);
        $stmt->execute();
        return $stmt->fetch(PDO::FETCH_ASSOC);
    }
}
?>